Câu hỏi 1: Kết quả của đoạn code dưới đây là bao nhiêu.

In [1]:
import torch
import torch.nn as nn

data = torch.Tensor ([1, 2, 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round ( output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

==> C

Câu hỏi 2: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [4]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)

        return x_exp/total
data = torch.Tensor ([5 , 2 , 4])
my_softmax = MySoftmax()
output = my_softmax ( data )
assert round (output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

==> B

Câu hỏi 3: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [5]:
data = torch.Tensor([1 , 2 , 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round (output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

==> C

Câu hỏi 4: Hoàn thành đoạn code sau đây theo công thức tính stable softmax.

In [6]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn . Module ):
    def __init__(self) :
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim = 0 ,keepdims = True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum (0, keepdims = True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[ -1].item(), 2) == 0.67
output


tensor([0.0900, 0.2447, 0.6652])

==> B

Câu hỏi 5: Một người (person) có thể là student, doctor, hoặc teacher. Một student gồm có name
(string), yob (int) (năm sinh), và grade (string). Các bạn thực hiện viết class Student theo mô tả
trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả
đầu ra là gì? Chọn đáp án đúng nhất bên dưới.

In [7]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob


class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.__grade = grade

    def describe(self):
        super().describe()
        print(
            f'Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.__grade}')

student1 = Student(name = "studentZ2023", yob =2011 , grade ="6")
assert student1._yob == 2011
student1.describe ()


Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


==> A

Câu hỏi 6: Một người (person) có thể là student, doctor, hoặc teacher. Một teacher gồm có name
(string), yob (int), và subject (string). Các bạn thực hiện viết class Teacher theo mô tả trên (Các
bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là
gì? Chọn đáp án đúng nhất bên dưới.


In [10]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob
    
class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.__subject = subject

    def describe(self):
        super().describe()
        print(
            f'Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.__subject}')

teacher1 = Teacher(name ="teacherZ2023", yob =1991 , subject ="History")
assert teacher1._yob == 1991
teacher1.describe ()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


==> B

Câu hỏi 7: Một người (person) có thể là student, doctor, hoặc teacher. Một doctor gồm có name
(string), yob (string), và specialist (string). Các bạn thực hiện viết class Teacher theo mô tả trên
(Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu
ra là gì? Chọn đáp án đúng nhất bên dưới.


In [12]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.__specialist = specialist

    def describe(self):
        super().describe()
        print(
            f'Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self.__specialist}')

doctor1 = Doctor(name ="doctorZ2023", yob = 1981 , specialist ="Endocrinologists ")
assert doctor1._yob == 1981
doctor1.describe ()


Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists 


==> A