Câu hỏi 1: Kết quả của đoạn code dưới đây là bao nhiêu.

In [1]:
import torch
import torch.nn as nn

data = torch.Tensor ([1, 2, 3])
softmax_function = nn.Softmax(dim =0)
output = softmax_function(data)
assert round ( output[0].item(), 2) == 0.09
output

tensor([0.0900, 0.2447, 0.6652])

==> C

Câu hỏi 2: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [4]:
class MySoftmax(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, x):
        x_exp = torch.exp(x)
        total = x_exp.sum(0, keepdims=True)

        return x_exp/total
data = torch.Tensor ([5 , 2 , 4])
my_softmax = MySoftmax()
output = my_softmax ( data )
assert round (output[-1].item(), 2) == 0.26
output

tensor([0.7054, 0.0351, 0.2595])

==> B

Câu hỏi 3: Hoàn thành đoạn code sau đây theo công thức tính softmax.

In [5]:
data = torch.Tensor([1 , 2 , 300000000])
my_softmax = MySoftmax()
output = my_softmax(data)
assert round (output[0].item(), 2) == 0.0
output

tensor([0., 0., nan])

==> C

Câu hỏi 4: Hoàn thành đoạn code sau đây theo công thức tính stable softmax.

In [6]:
import torch
import torch . nn as nn

class SoftmaxStable ( nn . Module ):
    def __init__(self) :
        super().__init__()

    def forward(self, x):
        x_max = torch.max(x, dim = 0 ,keepdims = True)
        x_exp = torch.exp(x - x_max.values)
        partition = x_exp.sum (0, keepdims = True)
        return x_exp / partition

data = torch.Tensor([1, 2, 3])
softmax_stable = SoftmaxStable()
output = softmax_stable(data)
assert round(output[ -1].item(), 2) == 0.67
output


tensor([0.0900, 0.2447, 0.6652])

==> B

Câu hỏi 5: Một người (person) có thể là student, doctor, hoặc teacher. Một student gồm có name
(string), yob (int) (năm sinh), và grade (string). Các bạn thực hiện viết class Student theo mô tả
trên (Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả
đầu ra là gì? Chọn đáp án đúng nhất bên dưới.

In [7]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob


class Student(Person):
    def __init__(self, name, yob, grade):
        super().__init__(name, yob)
        self.__grade = grade

    def describe(self):
        super().describe()
        print(
            f'Student - Name: {self._name} - YoB: {self._yob} - Grade: {self.__grade}')

student1 = Student(name = "studentZ2023", yob =2011 , grade ="6")
assert student1._yob == 2011
student1.describe ()


Student - Name: studentZ2023 - YoB: 2011 - Grade: 6


==> A

Câu hỏi 6: Một người (person) có thể là student, doctor, hoặc teacher. Một teacher gồm có name
(string), yob (int), và subject (string). Các bạn thực hiện viết class Teacher theo mô tả trên (Các
bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu ra là
gì? Chọn đáp án đúng nhất bên dưới.


In [10]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob
    
class Teacher(Person):
    def __init__(self, name, yob, subject):
        super().__init__(name, yob)
        self.__subject = subject

    def describe(self):
        super().describe()
        print(
            f'Teacher - Name: {self._name} - YoB: {self._yob} - Subject: {self.__subject}')

teacher1 = Teacher(name ="teacherZ2023", yob =1991 , subject ="History")
assert teacher1._yob == 1991
teacher1.describe ()

Teacher - Name: teacherZ2023 - YoB: 1991 - Subject: History


==> B

Câu hỏi 7: Một người (person) có thể là student, doctor, hoặc teacher. Một doctor gồm có name
(string), yob (string), và specialist (string). Các bạn thực hiện viết class Teacher theo mô tả trên
(Các bạn sẽ viết thêm describe() method để print ra tất cả thông tin của object) và kết quả đầu
ra là gì? Chọn đáp án đúng nhất bên dưới.


In [12]:
from abc import ABC , abstractmethod

class Person(ABC):
    def __init__(self, name, yob):
        self._name = name
        self._yob = yob

    @abstractmethod
    def describe(self):
        pass
    
    def get_yob(self):
        return self._yob

class Doctor(Person):
    def __init__(self, name, yob, specialist):
        super().__init__(name, yob)
        self.__specialist = specialist

    def describe(self):
        super().describe()
        print(
            f'Doctor - Name: {self._name} - YoB: {self._yob} - Specialist: {self.__specialist}')

doctor1 = Doctor(name ="doctorZ2023", yob = 1981 , specialist ="Endocrinologists ")
assert doctor1._yob == 1981
doctor1.describe ()


Doctor - Name: doctorZ2023 - YoB: 1981 - Specialist: Endocrinologists 


==> A

Câu hỏi 8 Một Ward gồm có name (string) và danh sách của mọi người trong Ward. Một người
person có thể là student, doctor, hoặc teacher và cần sử dụng một list để chứa danh sách của mọi
người trong Ward. Viết add_person(person) method trong Ward class để add thêm một người
mới với nghề nghiệp bất kỳ (student, teacher, doctor) vào danh sách người của ward. Tạo ra một
ward object, và thêm vào 1 student, 2 teacher, và 2 doctor. Thực hiện describe() method để in ra
tên ward (name) và toàn bộ thông tin của từng người trong ward. Chọn đáp án đúng nhất bên
dưới cho phương thức đếm số lượng doctor.


In [15]:
class Ward:
    def __init__(self, name):
        self.__name = name
        self.__list_people = list()

    def add_person(self, person: Person):
        self.__list_people.append(person)

    def describe(self):
        print(f'Name: {self.__name}')
        for p in self.__list_people:
            p.describe()

    def count_doctor(self):
        counter = 0
        for p in self.__list_people:
            if isinstance(p, Doctor):
                counter += 1
        return counter

student1 = Student( name =" studentA", yob =2010 , grade ="7")
teacher1 = Teacher( name =" teacherA", yob =1969 , subject ="Math")
teacher2 = Teacher( name =" teacherB", yob =1995 , subject ="History")
doctor1 = Doctor( name ="doctorA", yob =1945 , specialist ="Endocrinologists")
#assert ward1.count_doctor() == 1
doctor2 = Doctor(name ="doctorB", yob =1975, specialist ="Cardiologists")
ward1 = Ward(name =" Ward1 ")
ward1.add_person(student1)
ward1.add_person(teacher1)
ward1.add_person(teacher2)
ward1.add_person(doctor1)
ward1.add_person(doctor2)
ward1.count_doctor()


2

==> C

Câu hỏi 9 Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initial- ization
method nhận một input "capacity": dùng để khởi tạo stack với capacity là số lượng element mà
stack có thể chứa. .is_full(): kiểm tra stack đã full chưa. .push(value) add thêm value vào trong
stack. Kết quả đầu ra là gì?


In [16]:
class MyStack():
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []
    
    def is_empty(self):
        return len(self.__stack) == 0
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if self.is_full():
            raise Exception('The stack is full!')
        self.__stack.append(value)


stack1 = MyStack(capacity =5)
stack1.push(1)
assert stack1.is_full() == False
stack1.push(2)
print(stack1.is_full())



False


==> B

Câu hỏi 10: Thực hiện xây dựng class Stack với các chức năng (method) sau đây: initialization
method nhận một input "capacity", dùng để khởi tạo stack với capacity là số lượng element mà
stack có thể chứa. Phương thức is_empty(): kiểm tra stack có đang rỗng. Phương thức is_full():
kiểm tra stack đã full chưa. Phương thức push(value) add thêm value vào trong stack. Phương
thức top() lấy giá trị top element hiện tại của stack, nhưng không loại bỏ giá trị đó. Kết quả đầu
ra là gì?


In [18]:
class MyStack():
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__stack = []
    
    def is_empty(self):
        return len(self.__stack) == 0
    
    def is_full(self):
        return len(self.__stack) == self.__capacity
    
    def push(self, value):
        if self.is_full():
            raise Exception('The stack is full!')
        self.__stack.append(value)
    
    def top(self):
        if self.is_empty():
            raise Exception('The stack is empty!')
        return self.__stack[-1]


stack1 = MyStack(capacity = 5)
stack1.push (1)
assert stack1.is_full() == False
stack1.push (2)
print(stack1.top())



2


==> B

Câu hỏi 11: Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization
method nhận một input "capacity", dùng để khởi tạo queue với capacity là số lượng element mà
queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value)
add thêm value vào trong queue. Kết quả đầu ra là gì?


In [19]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    
    def is_empty(self):
        return len(self.__queue) == 0
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def enqueue(self, value):
        if self.is_full():
            raise Exception('Overflow')
        self.__queue.append(value)

queue1 = MyQueue(capacity = 5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.is_full () )

False


==> A

Câu hỏi 12: Thực hiện xây dựng class Queue với các chức năng (method) sau đây: initialization
method nhận một input "capacity" dùng để khởi tạo queue với capacity là số lượng element mà
queue có thể chứa. Phương thức is_full(): kiểm tra queue đã full chưa. Phương thức enqueue(value)
add thêm value vào trong queue. Phương thức front() lấy giá trị first element hiện tại của queue,
nhưng không loại bỏ giá trị đó. Kết quả đầu ra là gì?


In [20]:
class MyQueue:
    def __init__(self, capacity):
        self.__capacity = capacity
        self.__queue = []
    
    def is_empty(self):
        return len(self.__queue) == 0
    
    def is_full(self):
        return len(self.__queue) == self.__capacity
    
    def enqueue(self, value):
        if self.is_full():
            raise Exception('Overflow')
        self.__queue.append(value)
    
    def dequeue(self):
        if self.is_empty():
            raise Exception('Underflow')
        return self.__queue.pop(0)
    
    def front(self):
        if self.is_empty():
            raise Exception('Underflow')
        return self.__queue[0]

In [21]:
queue1 = MyQueue(capacity = 5)
queue1.enqueue(1)
assert queue1.is_full() == False
queue1.enqueue(2)
print(queue1.front())


1


==> D